PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tt: <http://jvsoest.eu/ontology/timeTrack.owl#>

select ?category ?hour (COUNT(*) AS ?minuteCount)
where {
    ?s tt:at_time ?dateTime.
    ?s tt:category ?category.
    BIND (hours(?dateTime) as ?hour).
}
GROUP BY ?category ?hour
ORDER BY ?category ?hour
