#!/bin/bash
source_folder=$1
volume_name=$2

if [ $# -lt 2 ]
then
    echo "Not enough arguments supplied\n\nUse dckrVolCopyIn <folder_path> <volume_name>"
    exit
fi

docker volume create $volume_name

docker run --rm \
    -v $volume_name:/volume/ \
    -v $source_folder:/source_folder/ \
    alpine sh -c "cp -R /source_folder/* /volume"
